language: python

install:
  - pip install tox coveralls

# command to run tests
script:
  tox

#env:
#  - TOXENV=py26
#  - TOXENV=py27
#  - TOXENV=py34
#  - TOXENV=py35
#  - TOXENV=py36

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

after_success:
  coveralls
